/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/base/Carousel.vue')['default']
    Desktop: typeof import('./src/components/Desktop.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    HolidayCarousel: typeof import('./src/components/HolidayCarousel.vue')['default']
    HotelCarousel: typeof import('./src/components/HotelCarousel.vue')['default']
    HotelItem: typeof import('./src/components/listitem/HotelItem.vue')['default']
    InertiaScroll: typeof import('./src/components/base/InertiaScroll.vue')['default']
    MapMark: typeof import('./src/components/base/MapMark.vue')['default']
    NewsCarousel: typeof import('./src/components/base/NewsCarousel.vue')['default']
    NewsListItem: typeof import('./src/components/listitem/NewsListItem.vue')['default']
    ProductCard: typeof import('./src/components/listitem/ProductCard.vue')['default']
    RetirementListItem: typeof import('./src/components/listitem/RetirementListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPull: typeof import('./src/components/base/ScrollPull.vue')['default']
    SearchInput: typeof import('./src/components/input/SearchInput.vue')['default']
    SmartScrollList: typeof import('./src/components/base/SmartScrollList.vue')['default']
    SmoothScroll: typeof import('./src/components/base/SmoothScroll.vue')['default']
    StoreListItem: typeof import('./src/components/listitem/StoreListItem.vue')['default']
    StudyActivityListItem: typeof import('./src/components/listitem/StudyActivityListItem.vue')['default']
    StudyPlanListItem: typeof import('./src/components/listitem/StudyPlanListItem.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    TourListItem: typeof import('./src/components/listitem/TourListItem.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
