/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/base/Carousel.vue')['default']
    Desktop: typeof import('./src/components/Desktop.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImg: typeof import('element-plus/es')['ElImg']
    HolidayCarousel: typeof import('./src/components/HolidayCarousel.vue')['default']
    HotelItem: typeof import('./src/components/hotel/HotelItem.vue')['default']
    InertiaScroll: typeof import('./src/components/base/InertiaScroll.vue')['default']
    MapMark: typeof import('./src/components/base/MapMark.vue')['default']
    NewsListItem: typeof import('./src/components/news/NewsListItem.vue')['default']
    ProductCard: typeof import('./src/components/shop/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPull: typeof import('./src/components/base/ScrollPull.vue')['default']
    SearchInput: typeof import('./src/components/input/SearchInput.vue')['default']
    SmartScrollList: typeof import('./src/components/base/SmartScrollList.vue')['default']
    SmoothScroll: typeof import('./src/components/base/SmoothScroll.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
