/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Desktop: typeof import('./src/components/Desktop.vue')['default']
    InertiaScroll: typeof import('./src/components/base/InertiaScroll.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPull: typeof import('./src/components/base/ScrollPull.vue')['default']
    SmartScrollList: typeof import('./src/components/base/SmartScrollList.vue')['default']
    SmoothScroll: typeof import('./src/components/base/SmoothScroll.vue')['default']
  }
}
